site_name: modbamtools
theme:
  features:
    - content.code.annotate
  name: null
  custom_dir: 'cinder'
  colorscheme: Material
nav:
  - Home: index.md
  - Commands: commands.md
  - Tutorial: tutorial.md
